server:
  port: 15443
  error:
    include-stacktrace: on_param
  ssl:
    protocol: TLS
    enabled-protocols: TLSv1.3
    bundle: eudi-rp-backend

spring:
  application:
    name: eudi-rp-backend-mock
  ssl:
    bundle:
      pem:
        eudi-rp-backend:
          key:
            alias: eudi-rp-backend.localhost
          keystore:
            certificate: classpath:eudi-rp-backend.localhost.crt
            private-key: classpath:eudi-rp-backend.localhost.key
          truststore:
            certificate: classpath:eudi-ca.localhost.crt
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:eudi-rp-backend
    username: sa
    password:
  main:
    banner-mode: off
  mvc:
    log-resolved-exception: false

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info
  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true

eudi:
  rp-backend:
    base-url: https://eudi-rp-backend.localhost:15443
    callback-url: https://eudi-rp.localhost:14443/presentation-callback
    ttl:
      request-uri: 60s
